//! Milkdrop's built-in noise textures (`noise_lq`, `noise_hq`, `noisevol_*`, …).
//!
//! Presets sample these for organic texture and turbulence. projectM ships them
//! as static assets generated by `MilkdropNoise`; we generate equivalent
//! deterministic value-noise on the CPU and upload them once. The low-quality
//! variants are per-texel white noise; the higher-quality variants are smoothed
//! so neighbouring texels correlate (closer to Milkdrop's bilinear-seeded set).

use pm_render::{GpuContext, Texture};

/// A deterministic splitmix64-style hash → one pseudo-random byte. Pure (no RNG
/// state, no `Math.random`) so the textures are identical every run.
fn hash_byte(mut x: u64) -> u8 {
    x = x.wrapping_add(0x9E3779B97F4A7C15);
    x = (x ^ (x >> 30)).wrapping_mul(0xBF58476D1CE4E5B9);
    x = (x ^ (x >> 27)).wrapping_mul(0x94D049BB133111EB);
    x ^= x >> 31;
    (x & 0xFF) as u8
}

fn rand_at(seed: u64, x: u32, y: u32, z: u32, channel: u32) -> u8 {
    let key = seed
        .wrapping_mul(0x100000001B3)
        ^ ((x as u64) << 1)
        ^ ((y as u64) << 21)
        ^ ((z as u64) << 42)
        ^ ((channel as u64) << 60);
    hash_byte(key)
}

/// Generate a `size×size` RGBA8 2D noise texture. `smooth` averages each texel
/// with its neighbours that many times (0 = raw white noise).
fn generate_2d(seed: u64, size: u32, smooth: u32) -> Vec<u8> {
    let n = (size * size) as usize;
    let mut data = vec![0u8; n * 4];
    for y in 0..size {
        for x in 0..size {
            let i = ((y * size + x) * 4) as usize;
            for c in 0..4 {
                data[i + c as usize] = rand_at(seed, x, y, 0, c);
            }
        }
    }
    for _ in 0..smooth {
        data = smooth_2d(&data, size);
    }
    data
}

/// One wrap-around 3×3 box blur pass over an RGBA8 2D image.
fn smooth_2d(src: &[u8], size: u32) -> Vec<u8> {
    let mut out = vec![0u8; src.len()];
    let s = size as i32;
    for y in 0..s {
        for x in 0..s {
            for c in 0..4 {
                let mut acc = 0u32;
                for dy in -1..=1 {
                    for dx in -1..=1 {
                        let xx = (x + dx).rem_euclid(s) as u32;
                        let yy = (y + dy).rem_euclid(s) as u32;
                        acc += src[((yy * size + xx) * 4 + c) as usize] as u32;
                    }
                }
                out[((y as u32 * size + x as u32) * 4 + c) as usize] = (acc / 9) as u8;
            }
        }
    }
    out
}

/// Generate a `size³` RGBA8 3D (volume) noise texture.
fn generate_3d(seed: u64, size: u32) -> Vec<u8> {
    let n = (size * size * size) as usize;
    let mut data = vec![0u8; n * 4];
    for z in 0..size {
        for y in 0..size {
            for x in 0..size {
                let i = (((z * size + y) * size + x) * 4) as usize;
                for c in 0..4 {
                    data[i + c as usize] = rand_at(seed, x, y, z, c);
                }
            }
        }
    }
    data
}

/// The standard set of Milkdrop noise textures, created once and bound to the
/// matching `sampler_noise_*` / `sampler_noisevol_*` names.
pub struct NoiseTextures {
    textures: Vec<Texture>,
}

impl NoiseTextures {
    pub fn new(ctx: &GpuContext) -> Self {
        let d = &ctx.device;
        let q = &ctx.queue;
        let tex2 = |name: &str, size: u32, smooth: u32, seed: u64| {
            Texture::from_rgba8(d, q, name, size, size, &generate_2d(seed, size, smooth))
        };
        let tex3 = |name: &str, size: u32, seed: u64| {
            Texture::from_rgba8_3d(d, q, name, size, size, size, &generate_3d(seed, size))
        };
        let textures = vec![
            tex2("sampler_noise_lq", 256, 0, 1),
            tex2("sampler_noise_lq_lite", 32, 0, 2),
            tex2("sampler_noise_mq", 256, 1, 3),
            tex2("sampler_noise_hq", 256, 2, 4),
            tex3("sampler_noisevol_lq", 32, 5),
            tex3("sampler_noisevol_hq", 32, 6),
        ];
        NoiseTextures { textures }
    }

    /// Find the noise texture bound to `name` (e.g. `sampler_noise_lq`), if any.
    pub fn get(&self, name: &str) -> Option<&Texture> {
        self.textures.iter().find(|t| t.name == name)
    }
}
