// Browser entry point. Boots the WebGPU visualizer, wires the audio sources
// (file / mic / tab), and drives a lightweight collapsible diagnostics panel.
//
// The `./pm_web/*` module is generated by `wasm-pack` (see package.json) and is
// git-ignored.
import init, {
  run,
  webgpu_supported,
  get_diagnostics,
  set_mouse,
  set_shader_source,
  set_pass_source,
  add_buffer_pass,
  remove_buffer_pass,
  set_pass_channel,
  reset_shader_buffers,
  project_json,
  export_scene,
  import_scene,
  midi_handle,
  midi_import,
  midi_export,
  midi_registry_json,
  midi_mappings_json,
  midi_set_mapping_field,
  midi_target_value,
  midi_take_actions,
  midi_take_updates,
} from './pm_web/pm_web.js';
import { AudioEngine } from './audio';
import { ControlsPanel } from './controls';
import { LayerPanel } from './layers';
import { EffectRack } from './effects-ui';
import { Recorder, WakeLock, toggleFullscreen } from './output';
import { copyShareUrl, loadFromUrl } from './share';
import { ProjectionManager } from './projection';
// Heavy UI modules are lazy-loaded on first open (code-splitting): the shader
// editor pulls in CodeMirror (~0.5 MB) and the MIDI panel its own bundle, so
// neither is downloaded before the first rendered frame.
import type { ShaderConsole } from './shader-console';
import type { MidiPanel } from './midi-ui';
import { parseMessage, PROTOCOL_VERSION } from './projection-protocol';
import { showAbout, maybeShowOnboarding } from './help';

const MIDI_KEY = 'pm-web-midi-v1';

let controlsPanel: ControlsPanel | null = null;
let layerPanel: LayerPanel | null = null;
let effectRack: EffectRack | null = null;
let midiPanel: MidiPanel | null = null;
let shaderConsole: ShaderConsole | null = null;
let projection: ProjectionManager | null = null;
const recorder = new Recorder();

// Lazy-load state for the code-split heavy panels.
let consoleLoading: Promise<ShaderConsole> | null = null;
let midiLoading: Promise<void> | null = null;
let pendingShader: { source: string; mode: number } | null = null;

/** Load the CodeMirror shader console on demand. */
async function ensureConsole(): Promise<ShaderConsole> {
  if (shaderConsole) return shaderConsole;
  if (!consoleLoading) {
    consoleLoading = (async () => {
      $('console-host').innerHTML = '<div class="sc-loading">Loading editor…</div>';
      const { ShaderConsole } = await import('./shader-console');
      const c = new ShaderConsole($('console-host'));
      c.onControls = (controls) => controlsPanel?.buildUserControls(controls);
      shaderConsole = c;
      if (pendingShader) {
        c.loadLayer(pendingShader.source, pendingShader.mode);
        pendingShader = null;
      }
      return c;
    })();
  }
  return consoleLoading;
}

/** Load the MIDI panel + Web-MIDI manager on demand. */
async function ensureMidi(): Promise<void> {
  if (midiPanel) return;
  if (!midiLoading) {
    midiLoading = (async () => {
      $('midi-host').innerHTML = '<div class="sc-loading">Loading MIDI…</div>';
      const [{ MidiManager }, { MidiPanel }] = await Promise.all([import('./midi'), import('./midi-ui')]);
      const p = new MidiPanel($('midi-host'), new MidiManager());
      p.onChange = saveMidi;
      midiPanel = p;
    })();
  }
  return midiLoading;
}

const canvas = document.getElementById('viz') as HTMLCanvasElement;

function resize(): void {
  const dpr = Math.min(window.devicePixelRatio || 1, 2);
  const w = Math.max(1, Math.floor(canvas.clientWidth * dpr));
  const h = Math.max(1, Math.floor(canvas.clientHeight * dpr));
  if (canvas.width !== w) canvas.width = w;
  if (canvas.height !== h) canvas.height = h;
}

function showFallback(detail?: string): void {
  if (detail) document.getElementById('fallback-msg')!.textContent = detail;
  document.getElementById('fallback')!.classList.add('show');
}

const $ = (id: string) => document.getElementById(id)!;

function setStatus(msg: string): void {
  $('audio-status').textContent = msg;
}

// --- Audio wiring ---------------------------------------------------------

const engine = new AudioEngine();

function wireAudioUI(): void {
  const fileInput = $('file-input') as HTMLInputElement;
  const transport = $('file-transport');
  const playPause = $('file-playpause') as HTMLButtonElement;
  const seek = $('file-seek') as HTMLInputElement;
  const loop = $('file-loop') as HTMLInputElement;

  fileInput.addEventListener('change', async () => {
    const file = fileInput.files?.[0];
    if (!file) return;
    try {
      const el = await engine.addFile(file);
      transport.style.display = 'flex';
      playPause.textContent = 'Pause';
      el.addEventListener('timeupdate', () => {
        if (el.duration) seek.value = String((el.currentTime / el.duration) * 1000);
      });
      el.addEventListener('play', () => (playPause.textContent = 'Pause'));
      el.addEventListener('pause', () => (playPause.textContent = 'Play'));
      setStatus(`Playing file: ${file.name}`);
    } catch (e) {
      setStatus(`File error: ${errMsg(e)}`);
    }
  });

  playPause.addEventListener('click', () => {
    const el = engine.fileElement();
    if (!el) return;
    if (el.paused) void el.play();
    else el.pause();
  });
  seek.addEventListener('input', () => {
    const el = engine.fileElement();
    if (el && el.duration) el.currentTime = (Number(seek.value) / 1000) * el.duration;
  });
  loop.addEventListener('change', () => {
    const el = engine.fileElement();
    if (el) el.loop = loop.checked;
  });

  // Media-capture capability detection. Some browsers (notably iOS Safari) do
  // not implement getDisplayMedia at all, and getUserMedia needs a secure
  // context — so feature-detect and disable the buttons rather than throwing a
  // raw "… is not a function" error on click.
  const micSupported = typeof navigator.mediaDevices?.getUserMedia === 'function';
  const displaySupported = typeof navigator.mediaDevices?.getDisplayMedia === 'function';
  const micBtn = $('mic-btn') as HTMLButtonElement;
  const tabBtn = $('tab-btn') as HTMLButtonElement;
  if (!micSupported) {
    micBtn.disabled = true;
    micBtn.title = "Microphone input isn't available in this browser/context.";
  }
  if (!displaySupported) {
    tabBtn.disabled = true;
    tabBtn.title = "Tab/system audio capture isn't supported on this browser (e.g. iOS Safari).";
  }

  micBtn.addEventListener('click', async () => {
    if (!micSupported) {
      setStatus("Microphone input isn't available in this browser");
      return;
    }
    if (engine.hasSource('mic')) {
      engine.removeSource('mic');
      setStatus('Microphone stopped');
      return;
    }
    try {
      await engine.enableMic();
      setStatus('Microphone active (not monitored to output)');
    } catch (e) {
      setStatus(`Mic error: ${errMsg(e)}`);
    }
  });

  tabBtn.addEventListener('click', async () => {
    if (!displaySupported) {
      setStatus("Tab/system audio capture isn't supported on this browser");
      return;
    }
    if (engine.hasSource('display')) {
      engine.removeSource('display');
      setStatus('Tab/system capture stopped');
      return;
    }
    try {
      await engine.enableDisplay();
      setStatus('Capturing tab/system audio');
    } catch (e) {
      setStatus(`Capture error: ${errMsg(e)}`);
    }
  });

  ($('master-gain') as HTMLInputElement).addEventListener('input', (e) => {
    engine.setMasterGain(Number((e.target as HTMLInputElement).value));
  });

  engine.onSourcesChanged = () => {
    ($('mic-btn') as HTMLButtonElement).classList.toggle('on', engine.hasSource('mic'));
    ($('tab-btn') as HTMLButtonElement).classList.toggle('on', engine.hasSource('display'));
    if (!engine.fileElement()) transport.style.display = 'none';
  };

  $('diag-toggle').addEventListener('click', () => $('diag').classList.toggle('collapsed'));

  document.addEventListener('visibilitychange', () => {
    if (!document.hidden) void engine.resume();
  });
}

function errMsg(e: unknown): string {
  return e instanceof Error ? e.message : String(e);
}

// --- Shader console + render-source selector ------------------------------

function wireUI(): void {
  controlsPanel = new ControlsPanel($('controls-host'));

  let selectedLayer: number | null = null;
  const lp = new LayerPanel($('layers-host'));
  layerPanel = lp;
  const er = new EffectRack($('effects-host'), () => selectedLayer);
  effectRack = er;
  er.onChanged = () => lp.save();

  layerPanel.onSelect = (kind, shader, layerId) => {
    selectedLayer = layerId;
    er.refresh();
    if (kind === 'shader') {
      // The shader already renders (in Rust); only sync the editor if it's open.
      if (shaderConsole) shaderConsole.loadLayer(shader.source, shader.mode);
      else pendingShader = { source: shader.source, mode: shader.mode };
      controlsPanel?.buildUserControls(shader.controls);
    } else {
      controlsPanel?.buildUserControls([]);
    }
  };

  // Console and Layers both dock on the left — keep them mutually exclusive.
  // Opening the console lazy-loads the editor bundle.
  $('console-btn').addEventListener('click', async () => {
    const willOpen = !$('console').classList.contains('open');
    if (willOpen) await ensureConsole();
    $('console').classList.toggle('open', willOpen);
    $('layers').classList.remove('open');
  });
  $('layers-btn').addEventListener('click', () => {
    $('layers').classList.toggle('open');
    $('console').classList.remove('open');
  });
  // Controls, Effects, MIDI, Output all dock on the right — mutually exclusive.
  const rightPanels = ['controls', 'effects', 'midi', 'output'];
  const openRight = (id: string) => {
    const wasOpen = $(id).classList.contains('open');
    rightPanels.forEach((p) => $(p).classList.remove('open'));
    if (!wasOpen) $(id).classList.add('open');
  };
  $('controls-btn').addEventListener('click', () => openRight('controls'));
  $('effects-btn').addEventListener('click', () => openRight('effects'));
  $('midi-btn').addEventListener('click', async () => {
    if (!$('midi').classList.contains('open')) await ensureMidi();
    openRight('midi');
  });
  $('output-btn').addEventListener('click', () => openRight('output'));
  $('help-btn').addEventListener('click', () => showAbout());

  wireOutput();
  wireProjection();
}

// --- Projection / second-screen output (Phase 8c) -------------------------

function wireProjection(): void {
  const proj = new ProjectionManager(canvas);
  projection = proj;
  const host = $('output-host');
  host.innerHTML = `
    <div class="op-row"><button id="op-open" class="primary">Open Output</button><button id="op-close">Close</button></div>
    <div class="op-status"><span class="op-dot" id="op-dot"></span><span id="op-state">No output window</span></div>
    <div class="op-row"><button id="op-resync">Re-sync</button><button id="op-front">Bring to front</button></div>
    <div class="op-row"><button id="op-clean">Clean Output (this window)</button></div>
    <p class="op-hint">Opens a separate window that mirrors the rendered visuals — no controls, ready for a projector or second monitor. Move it to the other display, then click its ⛶ Fullscreen button. Esc exits Clean Output here.</p>
    <div class="op-diag" id="op-diag"></div>`;

  const update = () => {
    const s = proj.status();
    const dot = $('op-dot');
    dot.className = 'op-dot' + (s.connected ? ' on' : s.open ? ' wait' : '');
    $('op-state').textContent = s.connected ? 'Output connected' : s.open ? 'Output open — connecting…' : 'No output window';
    $('op-diag').textContent = `source ${canvas.width}×${canvas.height} · frames served ${s.served}`;
  };
  proj.onStatus = update;

  $('op-open').addEventListener('click', () => {
    const r = proj.open();
    if (r === 'blocked') setStatus('Output window blocked — allow pop-ups for this site');
    else setStatus(r === 'exists' ? 'Output already open' : 'Output window opened');
    update();
  });
  $('op-close').addEventListener('click', () => { proj.close(); update(); });
  $('op-resync').addEventListener('click', () => proj.resync());
  $('op-front').addEventListener('click', () => proj.focusOutput());
  $('op-clean').addEventListener('click', () => setClean(!document.body.classList.contains('clean')));
  // Esc leaves Clean Output (the UI is hidden, so give a keyboard way out).
  window.addEventListener('keydown', (e) => {
    if (e.key === 'Escape' && document.body.classList.contains('clean')) setClean(false);
  });
  update();
  setInterval(update, 1000);
}

// Clean Output on the control window: hide all UI + auto-hide the cursor.
let cleanCursorTimer = 0;
function setClean(on: boolean): void {
  document.body.classList.toggle('clean', on);
  ($('op-clean') as HTMLButtonElement | null)?.classList.toggle('on', on);
  if (on) {
    const poke = () => {
      document.body.classList.remove('hide-cursor');
      clearTimeout(cleanCursorTimer);
      cleanCursorTimer = window.setTimeout(() => document.body.classList.add('hide-cursor'), 2500);
    };
    (window as unknown as { __pmCleanPoke?: () => void }).__pmCleanPoke = poke;
    window.addEventListener('pointermove', poke);
    poke();
  } else {
    const poke = (window as unknown as { __pmCleanPoke?: () => void }).__pmCleanPoke;
    if (poke) window.removeEventListener('pointermove', poke);
    clearTimeout(cleanCursorTimer);
    document.body.classList.remove('hide-cursor');
  }
}

// --- MIDI persistence + app-action dispatch -------------------------------

let midiSaveTimer = 0;
/** Persist mappings (debounced — mapping edits are user-paced, never per-message). */
function saveMidi(): void {
  clearTimeout(midiSaveTimer);
  midiSaveTimer = window.setTimeout(() => {
    try {
      localStorage.setItem(MIDI_KEY, midi_export());
    } catch {
      /* storage unavailable */
    }
  }, 200);
}

function toggleRecord(): void {
  recorder.toggle(canvas, engine.captureAudioStream());
}

/** Dispatch app-side MIDI actions (queued in Rust, decoupled from buttons) and
 *  reflect MIDI-driven values into whichever side panels are open. */
function midiTick(): void {
  try {
    const actions: string[] = JSON.parse(midi_take_actions());
    for (const a of actions) {
      if (a === 'record.toggle') toggleRecord();
      // future: scene.next / scene.prev / fullscreen …
    }
  } catch {
    /* ignore */
  }
  try {
    const u = JSON.parse(midi_take_updates()) as { values: unknown[]; bools: unknown[] };
    if (u.values.length || u.bools.length) {
      if ($('layers').classList.contains('open')) layerPanel?.syncValues();
      if ($('effects').classList.contains('open')) effectRack?.syncValues();
    }
  } catch {
    /* ignore */
  }
  midiPanel?.tick();
}

// --- Output & sharing: share URL, recording, fullscreen, wake lock --------

function wireOutput(): void {
  $('share-btn').addEventListener('click', async () => {
    setStatus(await copyShareUrl());
  });

  const recBtn = $('rec-btn') as HTMLButtonElement;
  recorder.onState = (on) => {
    recBtn.classList.toggle('on', on);
    recBtn.textContent = on ? '■ Stop' : 'Rec';
    setStatus(on ? 'Recording…' : 'Recording saved');
  };
  recBtn.addEventListener('click', toggleRecord);

  $('full-btn').addEventListener('click', () => void toggleFullscreen(canvas));

  const wake = new WakeLock();
  const wakeBtn = $('wake-btn') as HTMLButtonElement;
  if (!wake.supported) wakeBtn.style.display = 'none';
  wake.onState = (held) => wakeBtn.classList.toggle('on', held);
  wakeBtn.addEventListener('click', () => void wake.toggle());
}

// --- iMouse pointer handling ----------------------------------------------

function wireMouse(): void {
  let down = false;
  let click: [number, number] = [0, 0];
  // Canvas backing pixels, bottom-left origin (matches fragCoord after flip).
  const coords = (e: PointerEvent): [number, number] => {
    const rect = canvas.getBoundingClientRect();
    const dpr = Math.min(window.devicePixelRatio || 1, 2);
    const x = (e.clientX - rect.left) * dpr;
    const y = (rect.height - (e.clientY - rect.top)) * dpr;
    return [x, y];
  };
  const send = (cur: [number, number]) => {
    // Shadertoy iMouse: xy = current pos; z/w = click origin, negated when up.
    set_mouse(cur[0], cur[1], down ? click[0] : -click[0], down ? click[1] : -click[1]);
  };
  canvas.addEventListener('pointerdown', (e) => {
    down = true;
    click = coords(e);
    send(click);
  });
  canvas.addEventListener('pointermove', (e) => {
    if (down) send(coords(e));
  });
  window.addEventListener('pointerup', () => (down = false));
  canvas.addEventListener('pointerleave', () => (down = false));
}

// --- Diagnostics panel ----------------------------------------------------

function bar(v: number): string {
  const pct = Math.max(0, Math.min(1, v)) * 100;
  return `<span class="bar"><span style="width:${pct.toFixed(0)}%"></span></span>`;
}

let fpsLastFrame = 0;
let fpsLastTime = 0;
let fps = 0;

function updateDiagnostics(): void {
  let d: Record<string, number | boolean> = {};
  try {
    d = JSON.parse(get_diagnostics());
  } catch {
    /* wasm not ready */
  }
  // Render FPS from the frame-counter delta (smoothed).
  const now = performance.now();
  const frame = (d.frame as number) ?? 0;
  if (fpsLastTime && now > fpsLastTime) {
    const inst = ((frame - fpsLastFrame) * 1000) / (now - fpsLastTime);
    if (Number.isFinite(inst) && inst >= 0) fps = fps ? fps * 0.7 + inst * 0.3 : inst;
  }
  fpsLastFrame = frame;
  fpsLastTime = now;

  const s = engine.status();
  const rows: [string, string][] = [
    ['fps', `${fps.toFixed(0)} · ${((d.cpuMs as number) ?? 0).toFixed(1)} ms cpu`],
    ['layers', `${d.enabledCount ?? 0}/${d.layerCount ?? 0} on · ${d.shaderCount ?? 0} shader`],
    ['passes', `${d.shaderPasses ?? 0} shader · ${d.bufferPasses ?? 0} buffer · ${d.effectPasses ?? 0} effect`],
    ['iTime', `${((d.time as number) ?? 0).toFixed(2)} s`],
    ['speed', `${((d.scale as number) ?? 1).toFixed(2)}× ${d.paused ? '(paused)' : ''}`],
    ['frame', String(d.frame ?? 0)],
    ['resolution', `${d.width ?? 0}×${d.height ?? 0}`],
    ['BPM', `${((d.bpm as number) ?? 0).toFixed(0)} ${d.tempoManual ? '(man)' : '(auto)'}`],
    ['beat', `${bar(d.beatPulse as number)} phase ${((d.beatPhase as number) ?? 0).toFixed(2)}`],
    ['crossOriginIsolated', String(self.crossOriginIsolated === true)],
    ['transport', s.shared ? 'SharedArrayBuffer' : 'postMessage (fallback)'],
    ['AudioContext', s.contextState],
    ['sampleRate', `${d.sampleRate || s.sampleRate || 0} Hz`],
    ['sources', s.sources.join(', ') || '(none)'],
    ['channels', String(d.channels ?? 0)],
    ['ring fill', `${(((d.ringFill as number) ?? 0) * 100).toFixed(0)}%`],
    ['overruns', String(d.overruns ?? 0)],
    ['underruns', String(d.underruns ?? 0)],
    ['PCM consumed', String(d.consumed ?? 0)],
    ['bass', `${bar(d.bass as number)} ${((d.bass as number) ?? 0).toFixed(2)}`],
    ['mid', `${bar(d.mid as number)} ${((d.mid as number) ?? 0).toFixed(2)}`],
    ['treb', `${bar(d.treb as number)} ${((d.treb as number) ?? 0).toFixed(2)}`],
    ['vol', `${bar(d.vol as number)} ${((d.vol as number) ?? 0).toFixed(2)}`],
  ];
  $('diag-body').innerHTML = rows
    .map(([k, v]) => `<div class="row"><span class="k">${k}</span><span class="v">${v}</span></div>`)
    .join('');
  controlsPanel?.showBpm((d.bpm as number) ?? 0, Boolean(d.tempoManual));
}

// --- Boot -----------------------------------------------------------------

async function boot(): Promise<void> {
  resize();
  window.addEventListener('resize', resize);

  if (!('gpu' in navigator)) {
    showFallback();
    return;
  }
  await init();
  if (!webgpu_supported()) {
    showFallback();
    return;
  }
  try {
    await run('viz');
  } catch (e) {
    console.error(e);
    showFallback(`WebGPU initialization failed: ${errMsg(e)}`);
    return;
  }

  // Renderer is up. Audio is optional and must not affect it.
  const ui = $('ui');
  ui.style.display = 'flex';
  // The control bar wraps on narrow widths; keep the side panels docked exactly
  // above it (not under a hardcoded height) so they never cover the bar.
  const syncBarHeight = () =>
    document.documentElement.style.setProperty('--bar-h', `${ui.offsetHeight}px`);
  new ResizeObserver(syncBarHeight).observe(ui);
  syncBarHeight();
  wireAudioUI();
  wireUI();
  wireMouse();

  // A shared scene in the URL fragment overrides the locally-restored scene.
  if (await loadFromUrl()) {
    layerPanel?.refresh();
    layerPanel?.emitSelect();
    layerPanel?.save();
    setStatus('Loaded shared scene from URL');
  }

  // Restore saved MIDI mappings (kept globally, not per-scene).
  try {
    const savedMidi = localStorage.getItem(MIDI_KEY);
    if (savedMidi) midi_import(savedMidi);
  } catch {
    /* storage unavailable */
  }

  // Dev/test-only MIDI injection: forwards to the SAME handler real MIDI uses
  // (no privileged path). Enabled under Vite dev or an explicit ?miditest flag,
  // so the Playwright harness can synthesize messages without real hardware.
  const isDev = (import.meta as unknown as { env?: { DEV?: boolean } }).env?.DEV === true;
  if (isDev || location.search.includes('miditest')) {
    (window as unknown as Record<string, unknown>).__pmMidi = {
      inject: (device: string, status: number, d1: number, d2: number) => midi_handle(device, status, d1, d2),
      registry: () => midi_registry_json(),
      mappings: () => midi_mappings_json(),
      // Compile a shader into the selected layer (same export the console uses)
      // so tests can create a known control target without driving CodeMirror.
      compileSelected: (mode: number, src: string) => set_shader_source(mode, src),
      setField: (id: number, field: string, value: string) => midi_set_mapping_field(id, String(field), String(value)),
      value: (path: string) => JSON.parse(midi_target_value(path)),
    };
    // Projection protocol validation + live status, for harness assertions.
    (window as unknown as Record<string, unknown>).__pmProto = {
      VERSION: PROTOCOL_VERSION,
      parse: (d: unknown) => parseMessage(d),
    };
    (window as unknown as Record<string, unknown>).__pmProj = {
      status: () => projection?.status() ?? { open: false, connected: false, served: 0 },
      clean: () => document.body.classList.contains('clean'),
    };
    (window as unknown as Record<string, unknown>).__pmDiag = () => {
      try {
        return JSON.parse(get_diagnostics());
      } catch {
        return {};
      }
    };
    // Multipass shader project driving (wraps the same exports the console uses).
    (window as unknown as Record<string, unknown>).__pmShader = {
      project: () => JSON.parse(project_json()),
      setPass: (i: number, mode: number, src: string) => JSON.parse(set_pass_source(i, mode, src)),
      addBuffer: (i: number) => add_buffer_pass(i),
      removeBuffer: (i: number) => remove_buffer_pass(i),
      setChannel: (i: number, c: number, s: string) => set_pass_channel(i, c, s),
      resetBuffers: () => reset_shader_buffers(),
      exportScene: () => export_scene(),
      importScene: (j: string) => JSON.parse(import_scene(j)),
    };
    // Help/onboarding driving for the harness.
    (window as unknown as Record<string, unknown>).__pmHelp = {
      about: () => showAbout(),
      onboarding: () => {
        try {
          localStorage.removeItem('pm-web-onboarded-v1');
        } catch {
          /* ignore */
        }
        maybeShowOnboarding();
      },
      overlayShown: () => document.getElementById('pm-overlay')?.classList.contains('show') === true,
    };
  }

  setInterval(updateDiagnostics, 200);
  setInterval(midiTick, 100);

  // First-run welcome (once). Never blocks rendering. Suppressed under the test
  // flag so the harness isn't blocked by the overlay (it tests it explicitly).
  if (!location.search.includes('miditest')) maybeShowOnboarding();
}

void boot();
