// Browser entry point. Sizes the canvas (DPR-aware), checks for WebGPU, boots
// the wasm module, and shows the unsupported-WebGPU page on any failure.
//
// The `./pm_web/*` module is generated by `wasm-pack` (see package.json
// `wasm:dev` / `wasm:release`) and is git-ignored.
import init, { run, webgpu_supported } from './pm_web/pm_web.js';

const canvas = document.getElementById('viz') as HTMLCanvasElement;

/** Match the canvas backing store to its CSS size × devicePixelRatio (capped at
 *  2 to bound GPU cost). The Rust render loop reads canvas.width/height and
 *  reconfigures the surface when it changes. */
function resize(): void {
  const dpr = Math.min(window.devicePixelRatio || 1, 2);
  const w = Math.max(1, Math.floor(canvas.clientWidth * dpr));
  const h = Math.max(1, Math.floor(canvas.clientHeight * dpr));
  if (canvas.width !== w) canvas.width = w;
  if (canvas.height !== h) canvas.height = h;
}

function showFallback(detail?: string): void {
  if (detail) {
    // textContent (not innerHTML): never interpret error strings as markup.
    document.getElementById('fallback-msg')!.textContent = detail;
  }
  document.getElementById('fallback')!.classList.add('show');
}

async function boot(): Promise<void> {
  resize();
  window.addEventListener('resize', resize);

  // Fast path: browsers with no WebGPU at all, before loading wasm.
  if (!('gpu' in navigator)) {
    showFallback();
    return;
  }

  await init();
  if (!webgpu_supported()) {
    showFallback();
    return;
  }

  try {
    await run('viz');
  } catch (e) {
    console.error(e);
    showFallback(
      `WebGPU initialization failed: ${e instanceof Error ? e.message : String(e)}`,
    );
  }
}

void boot();
