// Browser entry point. Boots the WebGPU visualizer, wires the audio sources
// (file / mic / tab), and drives a lightweight collapsible diagnostics panel.
//
// The `./pm_web/*` module is generated by `wasm-pack` (see package.json) and is
// git-ignored.
import init, { run, webgpu_supported, get_diagnostics, set_mouse } from './pm_web/pm_web.js';
import { AudioEngine } from './audio';
import { ShaderConsole } from './shader-console';
import { ControlsPanel } from './controls';
import { LayerPanel } from './layers';
import { EffectRack } from './effects-ui';
import { Recorder, WakeLock, toggleFullscreen } from './output';
import { copyShareUrl, loadFromUrl } from './share';

let controlsPanel: ControlsPanel | null = null;
let layerPanel: LayerPanel | null = null;

const canvas = document.getElementById('viz') as HTMLCanvasElement;

function resize(): void {
  const dpr = Math.min(window.devicePixelRatio || 1, 2);
  const w = Math.max(1, Math.floor(canvas.clientWidth * dpr));
  const h = Math.max(1, Math.floor(canvas.clientHeight * dpr));
  if (canvas.width !== w) canvas.width = w;
  if (canvas.height !== h) canvas.height = h;
}

function showFallback(detail?: string): void {
  if (detail) document.getElementById('fallback-msg')!.textContent = detail;
  document.getElementById('fallback')!.classList.add('show');
}

const $ = (id: string) => document.getElementById(id)!;

function setStatus(msg: string): void {
  $('audio-status').textContent = msg;
}

// --- Audio wiring ---------------------------------------------------------

const engine = new AudioEngine();

function wireAudioUI(): void {
  const fileInput = $('file-input') as HTMLInputElement;
  const transport = $('file-transport');
  const playPause = $('file-playpause') as HTMLButtonElement;
  const seek = $('file-seek') as HTMLInputElement;
  const loop = $('file-loop') as HTMLInputElement;

  fileInput.addEventListener('change', async () => {
    const file = fileInput.files?.[0];
    if (!file) return;
    try {
      const el = await engine.addFile(file);
      transport.style.display = 'flex';
      playPause.textContent = 'Pause';
      el.addEventListener('timeupdate', () => {
        if (el.duration) seek.value = String((el.currentTime / el.duration) * 1000);
      });
      el.addEventListener('play', () => (playPause.textContent = 'Pause'));
      el.addEventListener('pause', () => (playPause.textContent = 'Play'));
      setStatus(`Playing file: ${file.name}`);
    } catch (e) {
      setStatus(`File error: ${errMsg(e)}`);
    }
  });

  playPause.addEventListener('click', () => {
    const el = engine.fileElement();
    if (!el) return;
    if (el.paused) void el.play();
    else el.pause();
  });
  seek.addEventListener('input', () => {
    const el = engine.fileElement();
    if (el && el.duration) el.currentTime = (Number(seek.value) / 1000) * el.duration;
  });
  loop.addEventListener('change', () => {
    const el = engine.fileElement();
    if (el) el.loop = loop.checked;
  });

  $('mic-btn').addEventListener('click', async () => {
    if (engine.hasSource('mic')) {
      engine.removeSource('mic');
      setStatus('Microphone stopped');
      return;
    }
    try {
      await engine.enableMic();
      setStatus('Microphone active (not monitored to output)');
    } catch (e) {
      setStatus(`Mic error: ${errMsg(e)}`);
    }
  });

  $('tab-btn').addEventListener('click', async () => {
    if (engine.hasSource('display')) {
      engine.removeSource('display');
      setStatus('Tab/system capture stopped');
      return;
    }
    try {
      await engine.enableDisplay();
      setStatus('Capturing tab/system audio');
    } catch (e) {
      setStatus(`Capture error: ${errMsg(e)}`);
    }
  });

  ($('master-gain') as HTMLInputElement).addEventListener('input', (e) => {
    engine.setMasterGain(Number((e.target as HTMLInputElement).value));
  });

  engine.onSourcesChanged = () => {
    ($('mic-btn') as HTMLButtonElement).classList.toggle('on', engine.hasSource('mic'));
    ($('tab-btn') as HTMLButtonElement).classList.toggle('on', engine.hasSource('display'));
    if (!engine.fileElement()) transport.style.display = 'none';
  };

  $('diag-toggle').addEventListener('click', () => $('diag').classList.toggle('collapsed'));

  document.addEventListener('visibilitychange', () => {
    if (!document.hidden) void engine.resume();
  });
}

function errMsg(e: unknown): string {
  return e instanceof Error ? e.message : String(e);
}

// --- Shader console + render-source selector ------------------------------

function wireUI(): void {
  controlsPanel = new ControlsPanel($('controls-host'));

  const shaderConsole = new ShaderConsole($('console-host'));
  shaderConsole.onControls = (controls) => controlsPanel?.buildUserControls(controls);

  let selectedLayer: number | null = null;
  const lp = new LayerPanel($('layers-host'));
  layerPanel = lp;
  const effectRack = new EffectRack($('effects-host'), () => selectedLayer);
  effectRack.onChanged = () => lp.save();

  layerPanel.onSelect = (kind, shader, layerId) => {
    selectedLayer = layerId;
    effectRack.refresh();
    if (kind === 'shader') {
      shaderConsole.loadLayer(shader.source, shader.mode);
      controlsPanel?.buildUserControls(shader.controls);
    } else {
      controlsPanel?.buildUserControls([]);
    }
  };

  // Console and Layers both dock on the left — keep them mutually exclusive.
  $('console-btn').addEventListener('click', () => {
    $('console').classList.toggle('open');
    $('layers').classList.remove('open');
  });
  $('layers-btn').addEventListener('click', () => {
    $('layers').classList.toggle('open');
    $('console').classList.remove('open');
  });
  // Controls and Effects both dock on the right — mutually exclusive.
  $('controls-btn').addEventListener('click', () => {
    $('controls').classList.toggle('open');
    $('effects').classList.remove('open');
  });
  $('effects-btn').addEventListener('click', () => {
    $('effects').classList.toggle('open');
    $('controls').classList.remove('open');
  });

  wireOutput();
}

// --- Output & sharing: share URL, recording, fullscreen, wake lock --------

function wireOutput(): void {
  $('share-btn').addEventListener('click', async () => {
    setStatus(await copyShareUrl());
  });

  const recorder = new Recorder();
  const recBtn = $('rec-btn') as HTMLButtonElement;
  recorder.onState = (on) => {
    recBtn.classList.toggle('on', on);
    recBtn.textContent = on ? '■ Stop' : 'Rec';
    setStatus(on ? 'Recording…' : 'Recording saved');
  };
  recBtn.addEventListener('click', () => recorder.toggle(canvas, engine.captureAudioStream()));

  $('full-btn').addEventListener('click', () => void toggleFullscreen(canvas));

  const wake = new WakeLock();
  const wakeBtn = $('wake-btn') as HTMLButtonElement;
  if (!wake.supported) wakeBtn.style.display = 'none';
  wake.onState = (held) => wakeBtn.classList.toggle('on', held);
  wakeBtn.addEventListener('click', () => void wake.toggle());
}

// --- iMouse pointer handling ----------------------------------------------

function wireMouse(): void {
  let down = false;
  let click: [number, number] = [0, 0];
  // Canvas backing pixels, bottom-left origin (matches fragCoord after flip).
  const coords = (e: PointerEvent): [number, number] => {
    const rect = canvas.getBoundingClientRect();
    const dpr = Math.min(window.devicePixelRatio || 1, 2);
    const x = (e.clientX - rect.left) * dpr;
    const y = (rect.height - (e.clientY - rect.top)) * dpr;
    return [x, y];
  };
  const send = (cur: [number, number]) => {
    // Shadertoy iMouse: xy = current pos; z/w = click origin, negated when up.
    set_mouse(cur[0], cur[1], down ? click[0] : -click[0], down ? click[1] : -click[1]);
  };
  canvas.addEventListener('pointerdown', (e) => {
    down = true;
    click = coords(e);
    send(click);
  });
  canvas.addEventListener('pointermove', (e) => {
    if (down) send(coords(e));
  });
  window.addEventListener('pointerup', () => (down = false));
  canvas.addEventListener('pointerleave', () => (down = false));
}

// --- Diagnostics panel ----------------------------------------------------

function bar(v: number): string {
  const pct = Math.max(0, Math.min(1, v)) * 100;
  return `<span class="bar"><span style="width:${pct.toFixed(0)}%"></span></span>`;
}

function updateDiagnostics(): void {
  let d: Record<string, number | boolean> = {};
  try {
    d = JSON.parse(get_diagnostics());
  } catch {
    /* wasm not ready */
  }
  const s = engine.status();
  const rows: [string, string][] = [
    ['layers', `${d.enabledCount ?? 0}/${d.layerCount ?? 0} on · ${d.shaderCount ?? 0} shader`],
    ['iTime', `${((d.time as number) ?? 0).toFixed(2)} s`],
    ['speed', `${((d.scale as number) ?? 1).toFixed(2)}× ${d.paused ? '(paused)' : ''}`],
    ['frame', String(d.frame ?? 0)],
    ['resolution', `${d.width ?? 0}×${d.height ?? 0}`],
    ['BPM', `${((d.bpm as number) ?? 0).toFixed(0)} ${d.tempoManual ? '(man)' : '(auto)'}`],
    ['beat', `${bar(d.beatPulse as number)} phase ${((d.beatPhase as number) ?? 0).toFixed(2)}`],
    ['crossOriginIsolated', String(self.crossOriginIsolated === true)],
    ['transport', s.shared ? 'SharedArrayBuffer' : 'postMessage (fallback)'],
    ['AudioContext', s.contextState],
    ['sampleRate', `${d.sampleRate || s.sampleRate || 0} Hz`],
    ['sources', s.sources.join(', ') || '(none)'],
    ['channels', String(d.channels ?? 0)],
    ['ring fill', `${(((d.ringFill as number) ?? 0) * 100).toFixed(0)}%`],
    ['overruns', String(d.overruns ?? 0)],
    ['underruns', String(d.underruns ?? 0)],
    ['PCM consumed', String(d.consumed ?? 0)],
    ['bass', `${bar(d.bass as number)} ${((d.bass as number) ?? 0).toFixed(2)}`],
    ['mid', `${bar(d.mid as number)} ${((d.mid as number) ?? 0).toFixed(2)}`],
    ['treb', `${bar(d.treb as number)} ${((d.treb as number) ?? 0).toFixed(2)}`],
    ['vol', `${bar(d.vol as number)} ${((d.vol as number) ?? 0).toFixed(2)}`],
  ];
  $('diag-body').innerHTML = rows
    .map(([k, v]) => `<div class="row"><span class="k">${k}</span><span class="v">${v}</span></div>`)
    .join('');
  controlsPanel?.showBpm((d.bpm as number) ?? 0, Boolean(d.tempoManual));
}

// --- Boot -----------------------------------------------------------------

async function boot(): Promise<void> {
  resize();
  window.addEventListener('resize', resize);

  if (!('gpu' in navigator)) {
    showFallback();
    return;
  }
  await init();
  if (!webgpu_supported()) {
    showFallback();
    return;
  }
  try {
    await run('viz');
  } catch (e) {
    console.error(e);
    showFallback(`WebGPU initialization failed: ${errMsg(e)}`);
    return;
  }

  // Renderer is up. Audio is optional and must not affect it.
  const ui = $('ui');
  ui.style.display = 'flex';
  // The control bar wraps on narrow widths; keep the side panels docked exactly
  // above it (not under a hardcoded height) so they never cover the bar.
  const syncBarHeight = () =>
    document.documentElement.style.setProperty('--bar-h', `${ui.offsetHeight}px`);
  new ResizeObserver(syncBarHeight).observe(ui);
  syncBarHeight();
  wireAudioUI();
  wireUI();
  wireMouse();

  // A shared scene in the URL fragment overrides the locally-restored scene.
  if (await loadFromUrl()) {
    layerPanel?.refresh();
    layerPanel?.emitSelect();
    layerPanel?.save();
    setStatus('Loaded shared scene from URL');
  }

  setInterval(updateDiagnostics, 200);
}

void boot();
